sudo: false
language: rust
rust:
- stable
- beta
- nightly
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  [ $TRAVIS_RUST_VERSION = stable ] &&
  cargo doc &&
  echo "<meta http-equiv=refresh content=0;url=keepass/index.html>" > target/doc/index.html &&
  pip install ghp-import --user &&
  ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
